### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified

### ISSUE THREAD

**Issue by cymilad** [qH0sT/AndroSpy#182]
I get this error while creating the file. Thank you, please help 

System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SV.Builder.RunProcess(String filename, String arguments) in C:\Users\Harun\source\repos\SV\SV\Builder.cs:line 140
   at SV.Builder.<build>b__3_0() in C:\Users\Harun\source\repos\SV\SV\Builder.cs:line 102

![image](https://user-images.githubusercontent.com/22496001/140641760-2b1e7af4-baf9-474f-9d7e-c84c4be991d4.png)

**Comment by cymilad** [comment]
> lol you haven't compiled the builder yet,that why's ,follows the instructions and you should be fine.

Where should I compile the builder?

**Comment by rockpapersissors** [comment]
> 
> 
> > lol you haven't compiled the builder yet,that why's ,follows the instructions and you should be fine.
> 
> Where should I compile the builder?

If you can't compile the builder , then what the fk u doing in here?

**Comment by runrungogo** [comment]
I've had the same problem. Have you solved it
