### ISSUE TITLE
Message=Could not find a part of the path 'C:\Users\SADDAM\Desktop\AndroSpy-master\Server\SV\bin\Debug\outs\20200809054215/tht/bin/Google_Hesap_Servisi.apk'.

### ISSUE THREAD

**Issue by 000saddamahmad** [qH0sT/AndroSpy#8]
System.IO.DirectoryNotFoundException
HResult=0x80070003
Message=Could not find a part of the path 'C:\Users\SADDAM\Desktop\AndroSpy-master\Server\SV\bin\Debug\outs\20200809054215/tht/bin/Google_Hesap_Servisi.apk'.
Source=mscorlib
StackTrace:
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
at SV.Builder.b__2_0() in C:\Users\SADDAM\Desktop\AndroSpy-master\Server\SV\Builder.cs:line 80
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()

**Comment by qH0sT** [comment]
have you re-configure paths in 'settings.tht' file for your system?

**Comment by 000saddamahmad** [comment]
Wait i mail u

**Comment by 000saddamahmad** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\zipalign.exe
C:\Program Files\Java\jdk-12.0.1\bin\jarsigner.exe
C:\Users\SADDAM\source\repos\SV\SV\bin\Debug\sound.wav

**Comment by kagami01** [comment]
Selam aylekum!!i got the same error below:
'C:\Users\User\Desktop\AndroSpy-master\AndroSpy-master\Server\SV\bin\Debug\outs\20200819182429/tht/bin/Google_Hesap_Servisi.apk'

do you have any advice to fix this issue??
Thank you in advance

**Comment by AibelKingslayer** [comment]
same issue is there any fix sir

**Comment by kagami01** [comment]
> same issue is there any fix sir

Selam aylekum.
did you checked your configuration file with the right path??i mean settings.tht' in "Debug" folder

**Comment by AibelKingslayer** [comment]
yes i have

**Comment by AibelKingslayer** [comment]
i have put the right path

**Comment by kagami01** [comment]
do you have discord??

**Comment by AibelKingslayer** [comment]
yess

**Comment by kagami01** [comment]
> yess

ok leave me your discord or sent me a message in pv

**Comment by AibelKingslayer** [comment]
your username or 4 digit tag?

**Comment by kagami01** [comment]
hello!
both

**Comment by AibelKingslayer** [comment]
ok give me

**Comment by kagami01** [comment]
kagami01#4704

**Comment by phleonarda** [comment]
Help me too. Same issue in version 3

**Comment by kamilababayeva** [comment]
Hi. I have the same issue too. Can someone help?

**Comment by Code06free** [comment]
Message=Could not find a part of the path 'C:\Users\myworks\Desktop\AndroSpy-master\Server\SV\bin\Debug\outs\20200809054215/tht/bin/Google_Hesap_Servisi.apk'

**Comment by 707321491** [comment]
Can you tell me the solution?
